### ISSUE TITLE
uncaught runtime errors: 'thread_id' undefined

### ISSUE THREAD

**Issue by luckandrew** [kiecodes/kiecodes-gpt-webapp#1]
Any idea why I might hit this?

![image](https://github.com/kiecodes/kiecodes-gpt-webapp/assets/35151780/b3681ab0-2f49-4d5f-8fc8-e6dee5a9bdcd)

**Comment by thekie** [comment]
Hey Andrew,

Thank you for bringing this issue to my attention.

I recently encountered a similar error, and it turned out to be due to another process running on port 8000. By terminating that process, I was able to resolve the issue. 

To address the problem you're facing, please ensure that no other processes are using port 8000. If there is a conflict, you have two options:

1. **Terminate the conflicting process**: This will free up port 8000 for your FastAPI application.

2. **Change the FastAPI port**: If you prefer not to or cannot stop the other process, you can run the FastAPI application on a different port. You can find instructions on how to do this in [this article](https://www.slingacademy.com/article/how-to-run-fastapi-on-a-custom-port).

If you opt to run FastAPI on a different port, you'll also need to update the port number in `app/services/api.js` for all fetch calls. Apologies for the inconvenience, as I didn't implement a `BASE_URL` constant to make this process easier.

I hope this helps resolve your issue. Feel free to reach out if you have any further questions or concerns.

Best regards,
Kie

**Comment by luckandrew** [comment]
Great - I changed the port from 8000 and use this command line arg to set the new port:

uvicorn main:app --port 3000

**Comment by thekie** [comment]
Hello again, since the react app is running on port 3000, you need to use a different port other than 3000. 

I would suggest port port 3001 for the python FastAPI part. But remember to also change the used port in the JS part as described in my first answer.

**Comment by thekie** [comment]
This issue was solved. I got confirmation via Discord . I am closing this issue now.
